import pygame

BACKGROUND_COLOR = (46, 52, 64)

TILE_BLOCK_SIZE = 25
TILE_COLOR = (3, 79, 132)
TILE_BORDER_COLOR = (0, 0, 0)

MOVING_TILE_COLOR = (255, 25, 25)
TILE_BORDER_WIDTH = 1
TILE_BORDER_RADIUS = 1

EXIT_DOOR_WIDTH = 25
EXIT_DOOR_HEIGHT = 50
EXIT_DOOR_BG_COLOR = 255, 255, 255
EXIT_DOOR_FRAME_BG_COLOR = 25, 25, 25

BLOCK_SIZE = 10
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
NUM_OF_BLOCKS_W = SCREEN_WIDTH / BLOCK_SIZE
NUM_OF_BLOCKS_H = SCREEN_HEIGHT / BLOCK_SIZE
DYING_DYE_INCREMENT = 10
BALL_RADIUS = 6
BOXING_DECREMENT = 3.5
GENERAL_BOXING_DECREMENT = 1

DEATH_LINE_HEIGHT = SCREEN_HEIGHT * 1.25
DEATH_LINE_HEIGHT_CEIL = -(SCREEN_HEIGHT * 1.25 - SCREEN_HEIGHT)

BITS_SPEED_RANGE = (-6, 6)
BITS_GRAVITY_DOWN = 0.15
BITS_COLOR = (3, 79, 132)
BITS_SIZE = (3,3)
BITS_NUMBER = 20

LASER_SEED_TIME = (1000, 3000)

BOUNCER_COLOR = (3, 79, 132)
BOUNCER_BORDER_COLOR = (25, 25, 25)

MOVING_PLATFORM_H_SPEED = 1.5
MOVING_PLATFORM_V_SPEED = 1.5

VGUN_WIDTH = 15
VGUN_HEIGHT = 25
VGUN_COLOR = (40, 40, 40)
VGUN_LASER_SPEED = 25

LASERV_WIDTH = 2
LASERV_HEIGHT = 4

NUM_OF_TILES_PER_ROW = SCREEN_WIDTH / TILE_BLOCK_SIZE
NUM_OF_TILE_ROWS = SCREEN_HEIGHT / TILE_BLOCK_SIZE

SPIKE_COLOR = (225, 225, 225)

FPS = 30

fpsClock = pygame.time.Clock()
screenBuffer = pygame.surface.Surface((SCREEN_WIDTH, SCREEN_HEIGHT))

GRAVITY_SPEED = 0.98

RAILTRACK_COLOR = (80, 80, 80)
RAILSAW_WIDTH = 15
RAILSAW_HEIGHT = 15
RAILSAW_RADIUS = 8
RAILSAW_SPEED = 4
RAIL_BOXING = 5

FADEOUT_ALPHA_SPEED = 1

MAIN_MENU_TEXT_COLOR = (255, 255, 255)

"""
    Bouncer Constants
"""
BOUNCER_V_FACTOR_BIG_BOUNCE = 1.6
BOUNCER_V_FACTOR_SMALL_BOUNCE = 0.4

BOUNCER_V_SPEED = 10.5
BOUNCER_H_SPEED = 5.25

"""
    Tile Enumeration Values
"""
TILE_NORMAL = 1
TILE_GREEN = 3
TILE_RED = 4
TILE_BLACK = 7
TILES_WITH_COLLISIONS = [TILE_NORMAL, TILE_GREEN, TILE_RED, TILE_BLACK]

TILE_SPIKES_UP = 2
TILE_SPIKES_LEFT = 5
TILE_SPIKES_RIGHT = 6
TILE_SPIKES_DOWN = 8
TILES_DEATH_COLLISIONS = [TILE_SPIKES_UP, TILE_SPIKES_LEFT, TILE_SPIKES_RIGHT, TILE_SPIKES_DOWN]

TILE_RAILTRACK_HORIZONTAL = 9
TILE_RAILTRACK_VERTICAL = 10
TILE_RAILTRACK_BOTTOM_LEFT = 11
TILE_RAILTRACK_TOP_LEFT = 12
TILE_RAILTRACK_TOP_RIGHT = 13
TILE_RAILTRACK_BOTTOM_RIGHT = 14

TILE_RAILTRACK_TOP_STOP = 15
TILE_RAILTRACK_RIGHT_STOP = 16
TILE_RAILTRACK_BOTTOM_STOP = 17
TILE_RAILTRACK_LEFT_STOP = 18

TILES_RAILTRACK_SYSTEM = [TILE_RAILTRACK_HORIZONTAL, TILE_RAILTRACK_VERTICAL, TILE_RAILTRACK_BOTTOM_LEFT, TILE_RAILTRACK_TOP_LEFT,
                          TILE_RAILTRACK_TOP_RIGHT, TILE_RAILTRACK_BOTTOM_RIGHT, TILE_RAILTRACK_TOP_STOP, TILE_RAILTRACK_RIGHT_STOP,
                          TILE_RAILTRACK_BOTTOM_STOP, TILE_RAILTRACK_LEFT_STOP]

