import pygame

BACKGROUND_COLOR = (46, 52, 64)

TILE_BLOCK_SIZE = 25
TILE_COLOR = (3, 79, 132)
TILE_BORDER_COLOR = (0, 0, 0)

MOVING_TILE_COLOR = (255, 25, 25)
TILE_BORDER_WIDTH = 1
TILE_BORDER_RADIUS = 1

EXIT_DOOR_WIDTH = 25
EXIT_DOOR_HEIGHT = 50
EXIT_DOOR_BG_COLOR = 255, 255, 255
EXIT_DOOR_FRAME_BG_COLOR = 25, 25, 25

BLOCK_SIZE = 10
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
NUM_OF_BLOCKS_W = SCREEN_WIDTH / BLOCK_SIZE
NUM_OF_BLOCKS_H = SCREEN_HEIGHT / BLOCK_SIZE
DYING_DYE_INCREMENT = 10
BALL_H_SPEED = 5
BALL_RADIUS = 6
BOXING_DECREMENT = 3.5
GENERAL_BOXING_DECREMENT = 1

DEATH_LINE_HEIGHT = SCREEN_HEIGHT * 1.25
BOUNCER_V_SPEED = 10.2

BITS_SPEED_RANGE = (-6, 6)
BITS_GRAVITY_DOWN = 0.15
BITS_COLOR = (3, 79, 132)
BITS_SIZE = (3,3)
BITS_NUMBER = 20

LASER_SEED_TIME = (1000, 3000)

BOUNCER_COLOR = (3, 79, 132)
BOUNCER_BORDER_COLOR = (25, 25, 25)

MOVING_PLATFORM_H_SPEED = 1.5
MOVING_PLATFORM_V_SPEED = 1.5

VGUN_WIDTH = 15
VGUN_HEIGHT = 40
VGUN_COLOR = (40, 40, 40)
VGUN_LASER_SPEED = 20

LASERV_WIDTH = 2
LASERV_HEIGHT = 4

NUM_OF_TILES_PER_ROW = SCREEN_WIDTH / TILE_BLOCK_SIZE
NUM_OF_TILE_ROWS =  SCREEN_HEIGHT / TILE_BLOCK_SIZE

FPS = 30

fpsClock = pygame.time.Clock()
screenBuffer = pygame.surface.Surface((SCREEN_WIDTH, SCREEN_HEIGHT))
